package test;

import com.fiacs.common.util.ByteUtil;

public class Test {
	public static void main(String[] args) {
		StringBuffer sb = new StringBuffer();
		sb.append("<ProtocolRoot type=\"8\" TotalCount=\"1\" CurrIndex=\"1\" SeqNum=\"149132550\" ><AuthorCode>2746E45B1EFB4FB5</AuthorCode><FingerID>210010001</FingerID><Id>1716</Id><InfoType>5</InfoType><OptionType>0</OptionType><data>FBlmAAAAknlhh6kPRMea5V2IWghFtgoHaYco6IN2EgO9iCnYQzRyEOKFCejCesKB6YeoBoPDs3dN"); 
		sb.append("iKsXQkXDi22FyQ9CAasSkoUa6AO62wmdhjkAwrorC9WICtgDMpOG5obdF0IFm4D5iLsXBQO0DhqG");
		sb.append("LeCCQEQMHogJ2MM0VBB2hi3ogzp7Fg2E+O/B+8sZ3oT64IE5pJCWhM7/AX90ENWGK+/E+vPfLolM");
		sb.append("CMW+M+bJikvvhP4U7CmKSufB/hQTcYT5D0LD5ALxiDkPyP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
		sb.append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
		sb.append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
		sb.append("AAAAAAAAAAAAAAAAAAAAAGGjZjeSWTGENLMjQzVnFmQ0EGMkP0EmMSJoEyo1JlIUcihTEmN1IWYh");
		sb.append("E0R0UyEzNPIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE2b9AANC"); 
		sb.append("RJDOXAFSpNC2HTCxrdDbUTVCy6CqVyJyypAYVjSEuZCtKhFDhqDrLhJyYYDOciVDQ7F5HECAuNCp");
		sb.append("ZSKBjZBrDhJ055D7THJUBYA9KFcgirGTZxYRi5FOD0Mx4IAWNCLFjMGzFzXgzaBPATA1IeAAAIWf");
		sb.append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); 
		sb.append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
		sb.append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
	sb.append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); 
		sb.append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); 
		sb.append("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
																	sb.append("</data></ProtocolRoot>");
																	String s1 = sb.toString();
		System.out.println(ByteUtil.bytesToHexString(s1.getBytes()).substring(0, ByteUtil.bytesToHexString(s1.getBytes()).length()));
		
		String s2 = "<ProtocolRoot type=\"8\" TotalCount=\"1\" CurrIndex=\"1\" SeqNum=\"149132552\" ><AuthorCode>0FDEDE5878046E94</AuthorCode><FingerID>220010001</FingerID><Id>1716</Id><InfoType>5</InfoType><OptionType>0</OptionType><data>FBNVAAAAcn05hljvEMuSWFqI9+/CxUp9voZXD4zJws+2iBcPAX5aCNmFVhDG8oNkXYe42EePi1th\r\n" + 
				"iMngwkU8Xw2J+P9BO6RvLYeH1obJNIhFhaf/QkEc4j6HaB/KcrTRQogpF0L6PGBhiLn4gwckdZKH\r\n" + 
				"ef+MCQOJIYWnAEIFawtFhScAxHBMEwmE9weA+XJZhYn4/4LB0xA2g/kXwsMAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAJZKPyRlWxI4UUVjNoN2bBNJNyOAMmIlURdYIkiGglNSAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEFV6GRSk\r\n" + 
				"3YEVIjXAmnHRUhEj03PwTAEU1WGxXAIVpHDqSAJk5YIkJxEAfXFbGCFzyJAPcVFFEnDANAVSI5Nt\r\n" + 
				"TCBQ6HBBOwJSQpBOFUE1vnAvcEBBjZBRD0IU4JADTGUA4HAAAAAAAAAAAAAAAAAAAAAAAAAAAF92\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"</data></ProtocolRoot>";
		System.out.println(ByteUtil.bytesToHexString(s2.getBytes()).substring(0, ByteUtil.bytesToHexString(s2.getBytes()).length()));
		String s3 = "FBlmAAAAknlhh6kPRMea5V2IWghFtgoHaYco6IN2EgO9iCnYQzRyEOKFCejCesKB6YeoBoPDs3dN\r\n" + 
				"iKsXQkXDi22FyQ9CAasSkoUa6AO62wmdhjkAwrorC9WICtgDMpOG5obdF0IFm4D5iLsXBQO0DhqG\r\n" + 
				"LeCCQEQMHogJ2MM0VBB2hi3ogzp7Fg2E+O/B+8sZ3oT64IE5pJCWhM7/AX90ENWGK+/E+vPfLolM\r\n" + 
				"CMW+M+bJikvvhP4U7CmKSufB/hQTcYT5D0LD5ALxiDkPyP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAGGjZjeSWTGENLMjQzVnFmQ0EGMkP0EmMSJoEyo1JlIUcihTEmN1IWYh\r\n" + 
				"E0R0UyEzNPIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE2b9AANC\r\n" + 
				"RJDOXAFSpNC2HTCxrdDbUTVCy6CqVyJyypAYVjSEuZCtKhFDhqDrLhJyYYDOciVDQ7F5HECAuNCp\r\n" + 
				"ZSKBjZBrDhJ055D7THJUBYA9KFcgirGTZxYRi5FOD0Mx4IAWNCLFjMGzFzXgzaBPATA1IeAAAIWf\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n" + 
				"";
		
		System.out.println(s3.length());
		
		String s4 = "aaaa";
		System.out.println(s4.length());
		
		String s5 = "aa\r\n"+
				"aa";
		System.out.println(s5.length());
	}
}
